start-at-login = true
after-login-command = ['workspace M']

after-startup-command = [
    'exec-and-forget borders active_color=0xffcba6f7 width=5.0 hidpi=on',
]
exec-on-workspace-change = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[workspace-to-monitor-force-assignment]
S = 'secondary'

[[on-window-detected]]
if.app-name-regex-substring = 'zen browser'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-name-regex-substring = 'wezterm'
run = 'move-node-to-workspace G'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-name-regex-substring = 'zed'
run = 'move-node-to-workspace Z'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 3
outer.bottom = 3
outer.top = 3
outer.right = 3

[mode.main.binding]

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating'

alt-slash = 'layout tiles horizontal vertical'
alt-period = 'layout accordion horizontal vertical'

alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

alt-ctrl-left = 'move left'
alt-ctrl-down = 'move down'
alt-ctrl-up = 'move up'
alt-ctrl-right = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-m = 'workspace M' # main workspace
alt-b = 'workspace B'
alt-g = 'workspace G'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-z = 'workspace Z'

alt-shift-m = 'move-node-to-workspace M' # main workspace
alt-shift-g = 'move-node-to-workspace G'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-z = 'move-node-to-workspace Z'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
alt-shift-enter = 'mode app'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-left = ['join-with left', 'mode main']
alt-shift-down = ['join-with down', 'mode main']
alt-shift-up = ['join-with up', 'mode main']
alt-shift-right = ['join-with right', 'mode main']

[mode.app.binding]
b = ['exec-and-forget open -a /Applications/Zen\ Browser.app', 'mode main']
g = ['exec-and-forget open -a /Applications/Wezterm.app', 'mode main']
s = ['exec-and-forget open -a /Applications/Slack.app', 'mode main']
t = ['exec-and-forget open -a /Applications/Telegram.app', 'mode main']
v = ['exec-and-forget open -a /Applications/OpenVPN\ Connect.app', 'mode main']
z = ['exec-and-forget open -a /Applications/Zed.app', 'mode main']
comma = [
    'exec-and-forget open -a /System/Applications/System\ Settings.app',
    'mode main',
]
esc = ['mode main']
