return {
  "echasnovski/mini.pick",
  version = false,
  cmd = "Pick",
  opts = {
    mappings = {
      caret_left = "<C-h>",
      caret_right = "<C-l>",
      choose = "<CR>",
      choose_in_split = "<C-s>",
      choose_in_tabpage = "<C-t>",
      choose_in_vsplit = "<C-v>",
      choose_marked = "<M-CR>",
      delete_char_right = "<Del>",
      delete_left = "<C-u>",
      delete_word = "<C-w>",
      mark = "<C-x>",
      mark_all = "<C-a>",
      move_down = "<C-n>",
      move_up = "<C-p>",
      paste = "<C-r>",
      refine = "<C-Space>",
      refine_marked = "<M-Space>",
      scroll_down = "<C-f>",
      scroll_up = "<C-b>",
      stop = "<Esc>",
      toggle_info = "<S-Tab>",
      toggle_preview = "<Tab>",
    },
  },
  keys = {
    { "<leader>ff", "<cmd>Pick files<cr>", desc = "Find Files" },
    { "<leader>fg", "<cmd>Pick grep_live<cr>", desc = "Live Grep" },
    { "<leader>fb", "<cmd>Pick buffers<cr>", desc = "Find Buffers" },
    { "<leader>fh", "<cmd>Pick help<cr>", desc = "Find Help" },
    { "<leader>fr", "<cmd>Pick resume<cr>", desc = "Resume" },
    { "<leader>/", "<cmd>Pick grep pattern='<cword>'<cr>", desc = "Grep Word" },
  },
}