# Shell and terminal tools
brew "starship"
brew "carapace"
brew "mcfly"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# CLI utilities and replacements
brew "btop"
brew "bat"
brew "eza"
brew "zoxide"
brew "ripgrep"
brew "fzf"
brew "yazi"
brew "wget"

# Development tools
brew "neovim"
brew "lazygit"
brew "fnm"
tap "oven-sh/bun"
brew "bun"

# System and media tools
brew "ffmpeg"
brew "hyperfine"
tap "FelixKratz/formulae"
brew "sketchybar"

cask "orbstack"
cask "obsidian"
cask "logi-options+"
cask "ghostty"
cask "zed"
cask "helium-browser"
cask "slack"
cask "telegram-desktop"
cask "font-comic-shanns-mono-nerd-font"
cask "nikitabobko/tap/aerospace"
cask "karabiner-elements"
cask "keycastr"
